package com.smartwasser.swrmq.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.smartwasser.swrmq.model.BcSysUser;
import com.smartwasser.swrmq.model.BcSysUserExample;

public interface RmqBcSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_user
     *
     * @mbggenerated Wed Jul 20 19:15:48 CST 2016
     */
    int countByExample(BcSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_user
     *
     * @mbggenerated Wed Jul 20 19:15:48 CST 2016
     */
    int deleteByExample(BcSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_user
     *
     * @mbggenerated Wed Jul 20 19:15:48 CST 2016
     */
    @Delete({
        "delete from bc_sys_user",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_user
     *
     * @mbggenerated Wed Jul 20 19:15:48 CST 2016
     */
    @Insert({
        "insert into bc_sys_user (ID, USERNAME, ",
        "PASSWORD, USERNAMECN, ",
        "EMAIL, STATE, LASTLOGINIP, ",
        "LASTLOGINTIME)",
        "values (#{id,jdbcType=VARCHAR}, #{username,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{usernamecn,jdbcType=VARCHAR}, ",
        "#{email,jdbcType=VARCHAR}, #{state,jdbcType=DECIMAL}, #{lastloginip,jdbcType=VARCHAR}, ",
        "#{lastlogintime,jdbcType=TIMESTAMP})"
    })
    int insert(BcSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_user
     *
     * @mbggenerated Wed Jul 20 19:15:48 CST 2016
     */
    int insertSelective(BcSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_user
     *
     * @mbggenerated Wed Jul 20 19:15:48 CST 2016
     */
    List<BcSysUser> selectByExample(BcSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_user
     *
     * @mbggenerated Wed Jul 20 19:15:48 CST 2016
     */
    @Select({
        "select",
        "ID, USERNAME, PASSWORD, USERNAMECN, EMAIL, STATE, LASTLOGINIP, LASTLOGINTIME",
        "from bc_sys_user",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    BcSysUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_user
     *
     * @mbggenerated Wed Jul 20 19:15:48 CST 2016
     */
    int updateByExampleSelective(@Param("record") BcSysUser record, @Param("example") BcSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_user
     *
     * @mbggenerated Wed Jul 20 19:15:48 CST 2016
     */
    int updateByExample(@Param("record") BcSysUser record, @Param("example") BcSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_user
     *
     * @mbggenerated Wed Jul 20 19:15:48 CST 2016
     */
    int updateByPrimaryKeySelective(BcSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_user
     *
     * @mbggenerated Wed Jul 20 19:15:48 CST 2016
     */
    @Update({
        "update bc_sys_user",
        "set USERNAME = #{username,jdbcType=VARCHAR},",
          "PASSWORD = #{password,jdbcType=VARCHAR},",
          "USERNAMECN = #{usernamecn,jdbcType=VARCHAR},",
          "EMAIL = #{email,jdbcType=VARCHAR},",
          "STATE = #{state,jdbcType=DECIMAL},",
          "LASTLOGINIP = #{lastloginip,jdbcType=VARCHAR},",
          "LASTLOGINTIME = #{lastlogintime,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BcSysUser record);
}