package com.smartwasser.swrmq.dao;

import com.smartwasser.swrmq.model.BcSysLog;
import com.smartwasser.swrmq.model.BcSysLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface RmqBcSysLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_LOG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    int countByExample(BcSysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_LOG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    int deleteByExample(BcSysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_LOG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    @Delete({
        "delete from BC_SYS_LOG",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_LOG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    @Insert({
        "insert into BC_SYS_LOG (ID, LOGOBJECT, ",
        "LOGTYPE, LOGKIND, ",
        "LOGDESC, OPERTYPE, ",
        "OPERUSER, OPERIP, ",
        "OPERDATE, OPERRESULT, ",
        "PLOGID)",
        "values (#{id,jdbcType=VARCHAR}, #{logobject,jdbcType=VARCHAR}, ",
        "#{logtype,jdbcType=DECIMAL}, #{logkind,jdbcType=DECIMAL}, ",
        "#{logdesc,jdbcType=VARCHAR}, #{opertype,jdbcType=VARCHAR}, ",
        "#{operuser,jdbcType=VARCHAR}, #{operip,jdbcType=VARCHAR}, ",
        "#{operdate,jdbcType=VARCHAR}, #{operresult,jdbcType=VARCHAR}, ",
        "#{plogid,jdbcType=LONGVARCHAR})"
    })
    int insert(BcSysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_LOG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    int insertSelective(BcSysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_LOG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    List<BcSysLog> selectByExampleWithBLOBs(BcSysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_LOG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    List<BcSysLog> selectByExample(BcSysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_LOG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    @Select({
        "select",
        "ID, LOGOBJECT, LOGTYPE, LOGKIND, LOGDESC, OPERTYPE, OPERUSER, OPERIP, OPERDATE, ",
        "OPERRESULT, PLOGID",
        "from BC_SYS_LOG",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("ResultMapWithBLOBs")
    BcSysLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_LOG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    int updateByExampleSelective(@Param("record") BcSysLog record, @Param("example") BcSysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_LOG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") BcSysLog record, @Param("example") BcSysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_LOG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    int updateByExample(@Param("record") BcSysLog record, @Param("example") BcSysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_LOG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    int updateByPrimaryKeySelective(BcSysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_LOG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    @Update({
        "update BC_SYS_LOG",
        "set LOGOBJECT = #{logobject,jdbcType=VARCHAR},",
          "LOGTYPE = #{logtype,jdbcType=DECIMAL},",
          "LOGKIND = #{logkind,jdbcType=DECIMAL},",
          "LOGDESC = #{logdesc,jdbcType=VARCHAR},",
          "OPERTYPE = #{opertype,jdbcType=VARCHAR},",
          "OPERUSER = #{operuser,jdbcType=VARCHAR},",
          "OPERIP = #{operip,jdbcType=VARCHAR},",
          "OPERDATE = #{operdate,jdbcType=VARCHAR},",
          "OPERRESULT = #{operresult,jdbcType=VARCHAR},",
          "PLOGID = #{plogid,jdbcType=LONGVARCHAR}",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(BcSysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_LOG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    @Update({
        "update BC_SYS_LOG",
        "set LOGOBJECT = #{logobject,jdbcType=VARCHAR},",
          "LOGTYPE = #{logtype,jdbcType=DECIMAL},",
          "LOGKIND = #{logkind,jdbcType=DECIMAL},",
          "LOGDESC = #{logdesc,jdbcType=VARCHAR},",
          "OPERTYPE = #{opertype,jdbcType=VARCHAR},",
          "OPERUSER = #{operuser,jdbcType=VARCHAR},",
          "OPERIP = #{operip,jdbcType=VARCHAR},",
          "OPERDATE = #{operdate,jdbcType=VARCHAR},",
          "OPERRESULT = #{operresult,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BcSysLog record);
}