package com.smartwasser.swrmq.dao;

import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

import com.smartwasser.swrmq.model.BcSysResourceRight;
import com.smartwasser.swrmq.model.BcSysResourceRightExample;

public interface RmqBcSysResourceRightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_resource_right
     *
     * @mbggenerated Wed Jul 20 19:16:34 CST 2016
     */
    int countByExample(BcSysResourceRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_resource_right
     *
     * @mbggenerated Wed Jul 20 19:16:34 CST 2016
     */
    int deleteByExample(BcSysResourceRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_resource_right
     *
     * @mbggenerated Wed Jul 20 19:16:34 CST 2016
     */
    @Insert({
        "insert into bc_sys_resource_right (ID, ROLEID, ",
        "RESOURCEID, FUNCID)",
        "values (#{id,jdbcType=VARCHAR}, #{roleid,jdbcType=VARCHAR}, ",
        "#{resourceid,jdbcType=VARCHAR}, #{funcid,jdbcType=VARCHAR})"
    })
    int insert(BcSysResourceRight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_resource_right
     *
     * @mbggenerated Wed Jul 20 19:16:34 CST 2016
     */
    int insertSelective(BcSysResourceRight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_resource_right
     *
     * @mbggenerated Wed Jul 20 19:16:34 CST 2016
     */
    List<BcSysResourceRight> selectByExample(BcSysResourceRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_resource_right
     *
     * @mbggenerated Wed Jul 20 19:16:34 CST 2016
     */
    int updateByExampleSelective(@Param("record") BcSysResourceRight record, @Param("example") BcSysResourceRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_resource_right
     *
     * @mbggenerated Wed Jul 20 19:16:34 CST 2016
     */
    int updateByExample(@Param("record") BcSysResourceRight record, @Param("example") BcSysResourceRightExample example);
}