package com.smartwasser.swrmq.dao;

import com.smartwasser.swrmq.model.BcSysOrg;
import com.smartwasser.swrmq.model.BcSysOrgExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface RmqBcSysOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_ORG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    int countByExample(BcSysOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_ORG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    int deleteByExample(BcSysOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_ORG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    @Delete({
        "delete from BC_SYS_ORG",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_ORG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    @Insert({
        "insert into BC_SYS_ORG (ID, DEPTNAME, ",
        "UPPERID, DEPTORDER, ",
        "DEPTCODE, CREATETIME, ",
        "CHDEPTMID)",
        "values (#{id,jdbcType=VARCHAR}, #{deptname,jdbcType=VARCHAR}, ",
        "#{upperid,jdbcType=VARCHAR}, #{deptorder,jdbcType=DECIMAL}, ",
        "#{deptcode,jdbcType=VARCHAR}, #{createtime,jdbcType=DATE}, ",
        "#{chdeptmid,jdbcType=DECIMAL})"
    })
    int insert(BcSysOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_ORG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    int insertSelective(BcSysOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_ORG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    List<BcSysOrg> selectByExample(BcSysOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_ORG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    @Select({
        "select",
        "ID, DEPTNAME, UPPERID, DEPTORDER, DEPTCODE, CREATETIME, CHDEPTMID",
        "from BC_SYS_ORG",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    BcSysOrg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_ORG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    int updateByExampleSelective(@Param("record") BcSysOrg record, @Param("example") BcSysOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_ORG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    int updateByExample(@Param("record") BcSysOrg record, @Param("example") BcSysOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_ORG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    int updateByPrimaryKeySelective(BcSysOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BC_SYS_ORG
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    @Update({
        "update BC_SYS_ORG",
        "set DEPTNAME = #{deptname,jdbcType=VARCHAR},",
          "UPPERID = #{upperid,jdbcType=VARCHAR},",
          "DEPTORDER = #{deptorder,jdbcType=DECIMAL},",
          "DEPTCODE = #{deptcode,jdbcType=VARCHAR},",
          "CREATETIME = #{createtime,jdbcType=DATE},",
          "CHDEPTMID = #{chdeptmid,jdbcType=DECIMAL}",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BcSysOrg record);
}