package com.smartwasser.swrmq.dao;

import com.smartwasser.swrmq.model.BcSysRoleusers;
import com.smartwasser.swrmq.model.BcSysRoleusersExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface RmqBcSysRoleusersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_roleusers
     *
     * @mbggenerated Wed Jul 20 19:15:58 CST 2016
     */
    int countByExample(BcSysRoleusersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_roleusers
     *
     * @mbggenerated Wed Jul 20 19:15:58 CST 2016
     */
    int deleteByExample(BcSysRoleusersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_roleusers
     *
     * @mbggenerated Wed Jul 20 19:15:58 CST 2016
     */
    @Insert({
        "insert into bc_sys_roleusers (ROLEID, USERID)",
        "values (#{roleid,jdbcType=VARCHAR}, #{userid,jdbcType=VARCHAR})"
    })
    int insert(BcSysRoleusers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_roleusers
     *
     * @mbggenerated Wed Jul 20 19:15:58 CST 2016
     */
    int insertSelective(BcSysRoleusers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_roleusers
     *
     * @mbggenerated Wed Jul 20 19:15:58 CST 2016
     */
    List<BcSysRoleusers> selectByExample(BcSysRoleusersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_roleusers
     *
     * @mbggenerated Wed Jul 20 19:15:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") BcSysRoleusers record, @Param("example") BcSysRoleusersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_roleusers
     *
     * @mbggenerated Wed Jul 20 19:15:58 CST 2016
     */
    int updateByExample(@Param("record") BcSysRoleusers record, @Param("example") BcSysRoleusersExample example);
}