package com.smartwasser.swrmq.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.smartwasser.swrmq.model.BcSysResource;
import com.smartwasser.swrmq.model.BcSysResourceExample;

public interface RmqBcSysResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_resource
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    int countByExample(BcSysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_resource
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    int deleteByExample(BcSysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_resource
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    @Delete({
        "delete from bc_sys_resource",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_resource
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    @Insert({
        "insert into bc_sys_resource (ID, PERMISSION, ",
        "NAME, URL_VAL, FUNC_ID, ",
        "ICON, SORT)",
        "values (#{id,jdbcType=VARCHAR}, #{permission,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{urlVal,jdbcType=VARCHAR}, #{funcId,jdbcType=VARCHAR}, ",
        "#{icon,jdbcType=VARCHAR}, #{sort,jdbcType=DECIMAL})"
    })
    int insert(BcSysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_resource
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    int insertSelective(BcSysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_resource
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    List<BcSysResource> selectByExample(BcSysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_resource
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    @Select({
        "select",
        "ID, PERMISSION, NAME, URL_VAL, FUNC_ID, ICON, SORT",
        "from bc_sys_resource",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    BcSysResource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_resource
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    int updateByExampleSelective(@Param("record") BcSysResource record, @Param("example") BcSysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_resource
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    int updateByExample(@Param("record") BcSysResource record, @Param("example") BcSysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_resource
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    int updateByPrimaryKeySelective(BcSysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_resource
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    @Update({
        "update bc_sys_resource",
        "set PERMISSION = #{permission,jdbcType=VARCHAR},",
          "NAME = #{name,jdbcType=VARCHAR},",
          "URL_VAL = #{urlVal,jdbcType=VARCHAR},",
          "FUNC_ID = #{funcId,jdbcType=VARCHAR},",
          "ICON = #{icon,jdbcType=VARCHAR},",
          "SORT = #{sort,jdbcType=DECIMAL}",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BcSysResource record);
}