package com.smartwasser.swrmq.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.smartwasser.swrmq.model.BcSysRight;
import com.smartwasser.swrmq.model.BcSysRightExample;

public interface RmqBcSysRightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_right
     *
     * @mbggenerated Wed Jul 20 19:16:23 CST 2016
     */
    int countByExample(BcSysRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_right
     *
     * @mbggenerated Wed Jul 20 19:16:23 CST 2016
     */
    int deleteByExample(BcSysRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_right
     *
     * @mbggenerated Wed Jul 20 19:16:23 CST 2016
     */
    @Delete({
        "delete from bc_sys_right",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_right
     *
     * @mbggenerated Wed Jul 20 19:16:23 CST 2016
     */
    @Insert({
        "insert into bc_sys_right (ID, ROLEID, ",
        "FUNCID, ACTIONID)",
        "values (#{id,jdbcType=VARCHAR}, #{roleid,jdbcType=VARCHAR}, ",
        "#{funcid,jdbcType=VARCHAR}, #{actionid,jdbcType=VARCHAR})"
    })
    int insert(BcSysRight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_right
     *
     * @mbggenerated Wed Jul 20 19:16:23 CST 2016
     */
    int insertSelective(BcSysRight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_right
     *
     * @mbggenerated Wed Jul 20 19:16:23 CST 2016
     */
    List<BcSysRight> selectByExample(BcSysRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_right
     *
     * @mbggenerated Wed Jul 20 19:16:23 CST 2016
     */
    @Select({
        "select",
        "ID, ROLEID, FUNCID, ACTIONID",
        "from bc_sys_right",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    BcSysRight selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_right
     *
     * @mbggenerated Wed Jul 20 19:16:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") BcSysRight record, @Param("example") BcSysRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_right
     *
     * @mbggenerated Wed Jul 20 19:16:23 CST 2016
     */
    int updateByExample(@Param("record") BcSysRight record, @Param("example") BcSysRightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_right
     *
     * @mbggenerated Wed Jul 20 19:16:23 CST 2016
     */
    int updateByPrimaryKeySelective(BcSysRight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_right
     *
     * @mbggenerated Wed Jul 20 19:16:23 CST 2016
     */
    @Update({
        "update bc_sys_right",
        "set ROLEID = #{roleid,jdbcType=VARCHAR},",
          "FUNCID = #{funcid,jdbcType=VARCHAR},",
          "ACTIONID = #{actionid,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BcSysRight record);
}