package com.smartwasser.swrmq.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.smartwasser.swrmq.model.BcSysRole;
import com.smartwasser.swrmq.model.BcSysRoleExample;

public interface RmqBcSysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_role
     *
     * @mbggenerated Wed Jul 20 19:16:12 CST 2016
     */
    int countByExample(BcSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_role
     *
     * @mbggenerated Wed Jul 20 19:16:12 CST 2016
     */
    int deleteByExample(BcSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_role
     *
     * @mbggenerated Wed Jul 20 19:16:12 CST 2016
     */
    @Delete({
        "delete from bc_sys_role",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_role
     *
     * @mbggenerated Wed Jul 20 19:16:12 CST 2016
     */
    @Insert({
        "insert into bc_sys_role (ID, ROLENAME, ",
        "ROLETYPE, PARENTID, ",
        "ROLELEVEL, ROLELEAF, ",
        "ROLEDESC)",
        "values (#{id,jdbcType=VARCHAR}, #{rolename,jdbcType=VARCHAR}, ",
        "#{roletype,jdbcType=VARCHAR}, #{parentid,jdbcType=VARCHAR}, ",
        "#{rolelevel,jdbcType=VARCHAR}, #{roleleaf,jdbcType=BIGINT}, ",
        "#{roledesc,jdbcType=LONGVARCHAR})"
    })
    int insert(BcSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_role
     *
     * @mbggenerated Wed Jul 20 19:16:12 CST 2016
     */
    int insertSelective(BcSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_role
     *
     * @mbggenerated Wed Jul 20 19:16:12 CST 2016
     */
    List<BcSysRole> selectByExampleWithBLOBs(BcSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_role
     *
     * @mbggenerated Wed Jul 20 19:16:12 CST 2016
     */
    List<BcSysRole> selectByExample(BcSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_role
     *
     * @mbggenerated Wed Jul 20 19:16:12 CST 2016
     */
    @Select({
        "select",
        "ID, ROLENAME, ROLETYPE, PARENTID, ROLELEVEL, ROLELEAF, ROLEDESC",
        "from bc_sys_role",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("ResultMapWithBLOBs")
    BcSysRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_role
     *
     * @mbggenerated Wed Jul 20 19:16:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") BcSysRole record, @Param("example") BcSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_role
     *
     * @mbggenerated Wed Jul 20 19:16:12 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") BcSysRole record, @Param("example") BcSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_role
     *
     * @mbggenerated Wed Jul 20 19:16:12 CST 2016
     */
    int updateByExample(@Param("record") BcSysRole record, @Param("example") BcSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_role
     *
     * @mbggenerated Wed Jul 20 19:16:12 CST 2016
     */
    int updateByPrimaryKeySelective(BcSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_role
     *
     * @mbggenerated Wed Jul 20 19:16:12 CST 2016
     */
    @Update({
        "update bc_sys_role",
        "set ROLENAME = #{rolename,jdbcType=VARCHAR},",
          "ROLETYPE = #{roletype,jdbcType=VARCHAR},",
          "PARENTID = #{parentid,jdbcType=VARCHAR},",
          "ROLELEVEL = #{rolelevel,jdbcType=VARCHAR},",
          "ROLELEAF = #{roleleaf,jdbcType=BIGINT},",
          "ROLEDESC = #{roledesc,jdbcType=LONGVARCHAR}",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(BcSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_role
     *
     * @mbggenerated Wed Jul 20 19:16:12 CST 2016
     */
    @Update({
        "update bc_sys_role",
        "set ROLENAME = #{rolename,jdbcType=VARCHAR},",
          "ROLETYPE = #{roletype,jdbcType=VARCHAR},",
          "PARENTID = #{parentid,jdbcType=VARCHAR},",
          "ROLELEVEL = #{rolelevel,jdbcType=VARCHAR},",
          "ROLELEAF = #{roleleaf,jdbcType=BIGINT}",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BcSysRole record);
}