package com.smartwasser.swrmq.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.smartwasser.swrmq.model.ClientUnitInfo;
import com.smartwasser.swrmq.model.ClientUnitInfoExample;

public interface RmqClientUnitInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_info
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    int countByExample(ClientUnitInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_info
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    int deleteByExample(ClientUnitInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_info
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    @Delete({
        "delete from client_unit_info",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_info
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    @Insert({
        "insert into client_unit_info (id, client_unit_name_ch, ",
        "client_unit_name_en, address, ",
        "second_level_domain, state, ",
        "create_time, creator, ",
        "update_time, remark, ",
        "del_flag, unitcode)",
        "values (#{id,jdbcType=VARCHAR}, #{clientUnitNameCh,jdbcType=VARCHAR}, ",
        "#{clientUnitNameEn,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{secondLevelDomain,jdbcType=VARCHAR}, #{state,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{creator,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{remark,jdbcType=VARCHAR}, ",
        "#{delFlag,jdbcType=VARCHAR}, #{unitcode,jdbcType=VARCHAR})"
    })
    int insert(ClientUnitInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_info
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    int insertSelective(ClientUnitInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_info
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    List<ClientUnitInfo> selectByExample(ClientUnitInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_info
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    @Select({
        "select",
        "id, client_unit_name_ch, client_unit_name_en, address, second_level_domain, ",
        "state, create_time, creator, update_time, remark, del_flag, unitcode",
        "from client_unit_info",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    ClientUnitInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_info
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") ClientUnitInfo record, @Param("example") ClientUnitInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_info
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    int updateByExample(@Param("record") ClientUnitInfo record, @Param("example") ClientUnitInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_info
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    int updateByPrimaryKeySelective(ClientUnitInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_info
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    @Update({
        "update client_unit_info",
        "set client_unit_name_ch = #{clientUnitNameCh,jdbcType=VARCHAR},",
          "client_unit_name_en = #{clientUnitNameEn,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "second_level_domain = #{secondLevelDomain,jdbcType=VARCHAR},",
          "state = #{state,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "del_flag = #{delFlag,jdbcType=VARCHAR},",
          "unitcode = #{unitcode,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ClientUnitInfo record);
}