package com.smartwasser.swrmq.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.smartwasser.swrmq.model.ClientUnitLinkman;
import com.smartwasser.swrmq.model.ClientUnitLinkmanExample;

public interface RmqClientUnitLinkmanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_linkman
     *
     * @mbggenerated Wed Jul 20 10:25:10 CST 2016
     */
    int countByExample(ClientUnitLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_linkman
     *
     * @mbggenerated Wed Jul 20 10:25:10 CST 2016
     */
    int deleteByExample(ClientUnitLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_linkman
     *
     * @mbggenerated Wed Jul 20 10:25:10 CST 2016
     */
    @Delete({
        "delete from client_unit_linkman",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_linkman
     *
     * @mbggenerated Wed Jul 20 10:25:10 CST 2016
     */
    @Insert({
        "insert into client_unit_linkman (id, linkman, ",
        "telephone, mobile_phone, ",
        "qq, weixin, email, ",
        "position, address, ",
        "fk_client_unit_id, state, ",
        "create_time, creator, ",
        "update_time, remark, ",
        "del_flag)",
        "values (#{id,jdbcType=VARCHAR}, #{linkman,jdbcType=VARCHAR}, ",
        "#{telephone,jdbcType=VARCHAR}, #{mobilePhone,jdbcType=VARCHAR}, ",
        "#{qq,jdbcType=VARCHAR}, #{weixin,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, ",
        "#{position,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{fkClientUnitId,jdbcType=VARCHAR}, #{state,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{creator,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{remark,jdbcType=VARCHAR}, ",
        "#{delFlag,jdbcType=VARCHAR})"
    })
    int insert(ClientUnitLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_linkman
     *
     * @mbggenerated Wed Jul 20 10:25:10 CST 2016
     */
    int insertSelective(ClientUnitLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_linkman
     *
     * @mbggenerated Wed Jul 20 10:25:10 CST 2016
     */
    List<ClientUnitLinkman> selectByExample(ClientUnitLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_linkman
     *
     * @mbggenerated Wed Jul 20 10:25:10 CST 2016
     */
    @Select({
        "select",
        "id, linkman, telephone, mobile_phone, qq, weixin, email, position, address, ",
        "fk_client_unit_id, state, create_time, creator, update_time, remark, del_flag",
        "from client_unit_linkman",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    ClientUnitLinkman selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_linkman
     *
     * @mbggenerated Wed Jul 20 10:25:10 CST 2016
     */
    int updateByExampleSelective(@Param("record") ClientUnitLinkman record, @Param("example") ClientUnitLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_linkman
     *
     * @mbggenerated Wed Jul 20 10:25:10 CST 2016
     */
    int updateByExample(@Param("record") ClientUnitLinkman record, @Param("example") ClientUnitLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_linkman
     *
     * @mbggenerated Wed Jul 20 10:25:10 CST 2016
     */
    int updateByPrimaryKeySelective(ClientUnitLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_unit_linkman
     *
     * @mbggenerated Wed Jul 20 10:25:10 CST 2016
     */
    @Update({
        "update client_unit_linkman",
        "set linkman = #{linkman,jdbcType=VARCHAR},",
          "telephone = #{telephone,jdbcType=VARCHAR},",
          "mobile_phone = #{mobilePhone,jdbcType=VARCHAR},",
          "qq = #{qq,jdbcType=VARCHAR},",
          "weixin = #{weixin,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "position = #{position,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "fk_client_unit_id = #{fkClientUnitId,jdbcType=VARCHAR},",
          "state = #{state,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "del_flag = #{delFlag,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ClientUnitLinkman record);
}