package com.smartwasser.swrmq.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.smartwasser.swrmq.model.ModelAccredit;
import com.smartwasser.swrmq.model.ModelAccreditExample;

public interface RmqModelAccreditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    int countByExample(ModelAccreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    int deleteByExample(ModelAccreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    @Delete({
        "delete from model_accredit",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    @Insert({
        "insert into model_accredit (id, fk_appid, ",
        "fk_sys_auth_id, state, ",
        "create_time, creator, ",
        "update_time, remark, ",
        "delflag)",
        "values (#{id,jdbcType=VARCHAR}, #{fkAppid,jdbcType=VARCHAR}, ",
        "#{fkSysAuthId,jdbcType=VARCHAR}, #{state,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{creator,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{remark,jdbcType=VARCHAR}, ",
        "#{delflag,jdbcType=VARCHAR})"
    })
    int insert(ModelAccredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    int insertSelective(ModelAccredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    List<ModelAccredit> selectByExample(ModelAccreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    @Select({
        "select",
        "id, fk_appid, fk_sys_auth_id, state, create_time, creator, update_time, remark, ",
        "delflag",
        "from model_accredit",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    ModelAccredit selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    int updateByExampleSelective(@Param("record") ModelAccredit record, @Param("example") ModelAccreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    int updateByExample(@Param("record") ModelAccredit record, @Param("example") ModelAccreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    int updateByPrimaryKeySelective(ModelAccredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    @Update({
        "update model_accredit",
        "set fk_appid = #{fkAppid,jdbcType=VARCHAR},",
          "fk_sys_auth_id = #{fkSysAuthId,jdbcType=VARCHAR},",
          "state = #{state,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "delflag = #{delflag,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ModelAccredit record);
}