package com.smartwasser.swrmq.dao;

import com.smartwasser.swrmq.model.MessageSendTask;
import com.smartwasser.swrmq.model.MessageSendTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface RmqMessageSendTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_send_task
     *
     * @mbggenerated Mon Jul 25 15:29:09 CST 2016
     */
    int countByExample(MessageSendTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_send_task
     *
     * @mbggenerated Mon Jul 25 15:29:09 CST 2016
     */
    int deleteByExample(MessageSendTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_send_task
     *
     * @mbggenerated Mon Jul 25 15:29:09 CST 2016
     */
    @Insert({
        "insert into message_send_task (data_id, data_table, ",
        "opt_type, send_time, ",
        "send_state, create_time)",
        "values (#{dataId,jdbcType=VARCHAR}, #{dataTable,jdbcType=VARCHAR}, ",
        "#{optType,jdbcType=VARCHAR}, #{sendTime,jdbcType=TIMESTAMP}, ",
        "#{sendState,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(MessageSendTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_send_task
     *
     * @mbggenerated Mon Jul 25 15:29:09 CST 2016
     */
    int insertSelective(MessageSendTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_send_task
     *
     * @mbggenerated Mon Jul 25 15:29:09 CST 2016
     */
    List<MessageSendTask> selectByExample(MessageSendTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_send_task
     *
     * @mbggenerated Mon Jul 25 15:29:09 CST 2016
     */
    int updateByExampleSelective(@Param("record") MessageSendTask record, @Param("example") MessageSendTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_send_task
     *
     * @mbggenerated Mon Jul 25 15:29:09 CST 2016
     */
    int updateByExample(@Param("record") MessageSendTask record, @Param("example") MessageSendTaskExample example);
}