package com.smartwasser.swrmq.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.smartwasser.swrmq.model.SubSysInfo;
import com.smartwasser.swrmq.model.SubSysInfoExample;
import com.smartwasser.swrmq.model.SubSysInfoKey;
import com.smartwasser.swrmq.model.SubSysInfoWithBLOBs;

public interface RmqSubSysInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_sys_info
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    int countByExample(SubSysInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_sys_info
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    int deleteByExample(SubSysInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_sys_info
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    @Delete({
        "delete from sub_sys_info",
        "where id = #{id,jdbcType=VARCHAR}",
          "and url = #{url,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(SubSysInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_sys_info
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    @Insert({
        "insert into sub_sys_info (id, url, ",
        "system_name_ch, system_name_en, ",
        "creator, del_flag, ",
        "update_time, create_time, ",
        "remark, icon_normal, ",
        "icon_click, icon_disable)",
        "values (#{id,jdbcType=VARCHAR}, #{url,jdbcType=VARCHAR}, ",
        "#{systemNameCh,jdbcType=VARCHAR}, #{systemNameEn,jdbcType=VARCHAR}, ",
        "#{creator,jdbcType=VARCHAR}, #{delFlag,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{remark,jdbcType=VARCHAR}, #{iconNormal,jdbcType=LONGVARBINARY}, ",
        "#{iconClick,jdbcType=LONGVARBINARY}, #{iconDisable,jdbcType=LONGVARBINARY})"
    })
    int insert(SubSysInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_sys_info
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    int insertSelective(SubSysInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_sys_info
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    List<SubSysInfoWithBLOBs> selectByExampleWithBLOBs(SubSysInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_sys_info
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    List<SubSysInfo> selectByExample(SubSysInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_sys_info
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    @Select({
        "select",
        "id, url, system_name_ch, system_name_en, creator, del_flag, update_time, create_time, ",
        "remark, icon_normal, icon_click, icon_disable",
        "from sub_sys_info",
        "where id = #{id,jdbcType=VARCHAR}",
          "and url = #{url,jdbcType=VARCHAR}"
    })
    @ResultMap("ResultMapWithBLOBs")
    SubSysInfoWithBLOBs selectByPrimaryKey(SubSysInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_sys_info
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    int updateByExampleSelective(@Param("record") SubSysInfoWithBLOBs record, @Param("example") SubSysInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_sys_info
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") SubSysInfoWithBLOBs record, @Param("example") SubSysInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_sys_info
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    int updateByExample(@Param("record") SubSysInfo record, @Param("example") SubSysInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_sys_info
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    int updateByPrimaryKeySelective(SubSysInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_sys_info
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    @Update({
        "update sub_sys_info",
        "set system_name_ch = #{systemNameCh,jdbcType=VARCHAR},",
          "system_name_en = #{systemNameEn,jdbcType=VARCHAR},",
          "creator = #{creator,jdbcType=VARCHAR},",
          "del_flag = #{delFlag,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "icon_normal = #{iconNormal,jdbcType=LONGVARBINARY},",
          "icon_click = #{iconClick,jdbcType=LONGVARBINARY},",
          "icon_disable = #{iconDisable,jdbcType=LONGVARBINARY}",
        "where id = #{id,jdbcType=VARCHAR}",
          "and url = #{url,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(SubSysInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_sys_info
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    @Update({
        "update sub_sys_info",
        "set system_name_ch = #{systemNameCh,jdbcType=VARCHAR},",
          "system_name_en = #{systemNameEn,jdbcType=VARCHAR},",
          "creator = #{creator,jdbcType=VARCHAR},",
          "del_flag = #{delFlag,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}",
          "and url = #{url,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SubSysInfo record);
}