package com.smartwasser.swrmq.dao;

import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

import com.smartwasser.swrmq.model.SystemAllocation;
import com.smartwasser.swrmq.model.SystemAllocationExample;

public interface RmqSystemAllocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_allocation
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    int countByExample(SystemAllocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_allocation
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    int deleteByExample(SystemAllocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_allocation
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    @Insert({
        "insert into system_allocation (fk_system_id, user_id, ",
        "allocation_person, create_time, ",
        "fk_business_unit_code)",
        "values (#{fkSystemId,jdbcType=VARCHAR}, #{userId,jdbcType=VARCHAR}, ",
        "#{allocationPerson,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{fkBusinessUnitCode,jdbcType=VARCHAR})"
    })
    int insert(SystemAllocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_allocation
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    int insertSelective(SystemAllocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_allocation
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    List<SystemAllocation> selectByExample(SystemAllocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_allocation
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") SystemAllocation record, @Param("example") SystemAllocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_allocation
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    int updateByExample(@Param("record") SystemAllocation record, @Param("example") SystemAllocationExample example);
}