package com.smartwasser.swrmq.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.smartwasser.swrmq.model.SystemAccredit;
import com.smartwasser.swrmq.model.SystemAccreditExample;

public interface RmqSystemAccreditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    int countByExample(SystemAccreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    int deleteByExample(SystemAccreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    @Delete({
        "delete from system_accredit",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    @Insert({
        "insert into system_accredit (id, fk_business_unit_code, ",
        "fk_system_id, fk_schema_id, ",
        "state, create_time, ",
        "creator, update_time, ",
        "remark, del_flag)",
        "values (#{id,jdbcType=VARCHAR}, #{fkBusinessUnitCode,jdbcType=VARCHAR}, ",
        "#{fkSystemId,jdbcType=VARCHAR}, #{fkSchemaId,jdbcType=VARCHAR}, ",
        "#{state,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{creator,jdbcType=VARCHAR}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{remark,jdbcType=VARCHAR}, #{delFlag,jdbcType=VARCHAR})"
    })
    int insert(SystemAccredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    int insertSelective(SystemAccredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    List<SystemAccredit> selectByExample(SystemAccreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    @Select({
        "select",
        "id, fk_business_unit_code, fk_system_id, fk_schema_id, state, create_time, creator, ",
        "update_time, remark, del_flag",
        "from system_accredit",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    SystemAccredit selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    int updateByExampleSelective(@Param("record") SystemAccredit record, @Param("example") SystemAccreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    int updateByExample(@Param("record") SystemAccredit record, @Param("example") SystemAccreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    int updateByPrimaryKeySelective(SystemAccredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    @Update({
        "update system_accredit",
        "set fk_business_unit_code = #{fkBusinessUnitCode,jdbcType=VARCHAR},",
          "fk_system_id = #{fkSystemId,jdbcType=VARCHAR},",
          "fk_schema_id = #{fkSchemaId,jdbcType=VARCHAR},",
          "state = #{state,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "del_flag = #{delFlag,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SystemAccredit record);
}