package com.smartwasser.swrmq.model;

import java.util.Date;

public class BcSysFunc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_func.ID
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_func.APPID
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_func.PARENTID
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_func.FUNCNAMECH
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    private String funcnamech;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_func.FUNCNAMEEN
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    private String funcnameen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_func.FUNCURL
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    private String funcurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_func.FUNCDESC
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    private String funcdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_func.FUNCCODE
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    private String funccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_func.PRIORITY
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    private Long priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_func.ISMENU
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    private Short ismenu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_func.CREATETIME
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_func.CHFUNCMID
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    private Long chfuncmid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_func.isapp
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    private String isapp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_func.ID
     *
     * @return the value of bc_sys_func.ID
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_func.ID
     *
     * @param id the value for bc_sys_func.ID
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_func.APPID
     *
     * @return the value of bc_sys_func.APPID
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_func.APPID
     *
     * @param appid the value for bc_sys_func.APPID
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_func.PARENTID
     *
     * @return the value of bc_sys_func.PARENTID
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_func.PARENTID
     *
     * @param parentid the value for bc_sys_func.PARENTID
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_func.FUNCNAMECH
     *
     * @return the value of bc_sys_func.FUNCNAMECH
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public String getFuncnamech() {
        return funcnamech;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_func.FUNCNAMECH
     *
     * @param funcnamech the value for bc_sys_func.FUNCNAMECH
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public void setFuncnamech(String funcnamech) {
        this.funcnamech = funcnamech == null ? null : funcnamech.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_func.FUNCNAMEEN
     *
     * @return the value of bc_sys_func.FUNCNAMEEN
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public String getFuncnameen() {
        return funcnameen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_func.FUNCNAMEEN
     *
     * @param funcnameen the value for bc_sys_func.FUNCNAMEEN
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public void setFuncnameen(String funcnameen) {
        this.funcnameen = funcnameen == null ? null : funcnameen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_func.FUNCURL
     *
     * @return the value of bc_sys_func.FUNCURL
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public String getFuncurl() {
        return funcurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_func.FUNCURL
     *
     * @param funcurl the value for bc_sys_func.FUNCURL
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public void setFuncurl(String funcurl) {
        this.funcurl = funcurl == null ? null : funcurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_func.FUNCDESC
     *
     * @return the value of bc_sys_func.FUNCDESC
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public String getFuncdesc() {
        return funcdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_func.FUNCDESC
     *
     * @param funcdesc the value for bc_sys_func.FUNCDESC
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public void setFuncdesc(String funcdesc) {
        this.funcdesc = funcdesc == null ? null : funcdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_func.FUNCCODE
     *
     * @return the value of bc_sys_func.FUNCCODE
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public String getFunccode() {
        return funccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_func.FUNCCODE
     *
     * @param funccode the value for bc_sys_func.FUNCCODE
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public void setFunccode(String funccode) {
        this.funccode = funccode == null ? null : funccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_func.PRIORITY
     *
     * @return the value of bc_sys_func.PRIORITY
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public Long getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_func.PRIORITY
     *
     * @param priority the value for bc_sys_func.PRIORITY
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public void setPriority(Long priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_func.ISMENU
     *
     * @return the value of bc_sys_func.ISMENU
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public Short getIsmenu() {
        return ismenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_func.ISMENU
     *
     * @param ismenu the value for bc_sys_func.ISMENU
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public void setIsmenu(Short ismenu) {
        this.ismenu = ismenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_func.CREATETIME
     *
     * @return the value of bc_sys_func.CREATETIME
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_func.CREATETIME
     *
     * @param createtime the value for bc_sys_func.CREATETIME
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_func.CHFUNCMID
     *
     * @return the value of bc_sys_func.CHFUNCMID
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public Long getChfuncmid() {
        return chfuncmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_func.CHFUNCMID
     *
     * @param chfuncmid the value for bc_sys_func.CHFUNCMID
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public void setChfuncmid(Long chfuncmid) {
        this.chfuncmid = chfuncmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_func.isapp
     *
     * @return the value of bc_sys_func.isapp
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public String getIsapp() {
        return isapp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_func.isapp
     *
     * @param isapp the value for bc_sys_func.isapp
     *
     * @mbggenerated Thu Jul 21 18:22:19 CST 2016
     */
    public void setIsapp(String isapp) {
        this.isapp = isapp == null ? null : isapp.trim();
    }
}