package com.smartwasser.swrmq.model;

public class BcSysRoleusers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_roleusers.ROLEID
     *
     * @mbggenerated Wed Jul 20 19:15:58 CST 2016
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_roleusers.USERID
     *
     * @mbggenerated Wed Jul 20 19:15:58 CST 2016
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_roleusers.ROLEID
     *
     * @return the value of bc_sys_roleusers.ROLEID
     *
     * @mbggenerated Wed Jul 20 19:15:58 CST 2016
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_roleusers.ROLEID
     *
     * @param roleid the value for bc_sys_roleusers.ROLEID
     *
     * @mbggenerated Wed Jul 20 19:15:58 CST 2016
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_roleusers.USERID
     *
     * @return the value of bc_sys_roleusers.USERID
     *
     * @mbggenerated Wed Jul 20 19:15:58 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_roleusers.USERID
     *
     * @param userid the value for bc_sys_roleusers.USERID
     *
     * @mbggenerated Wed Jul 20 19:15:58 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }
}