package com.smartwasser.swrmq.model;

import java.math.BigDecimal;

public class BcSysLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_SYS_LOG.ID
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_SYS_LOG.LOGOBJECT
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    private String logobject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_SYS_LOG.LOGTYPE
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    private BigDecimal logtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_SYS_LOG.LOGKIND
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    private BigDecimal logkind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_SYS_LOG.LOGDESC
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    private String logdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_SYS_LOG.OPERTYPE
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    private String opertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_SYS_LOG.OPERUSER
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    private String operuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_SYS_LOG.OPERIP
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    private String operip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_SYS_LOG.OPERDATE
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    private String operdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_SYS_LOG.OPERRESULT
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    private String operresult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_SYS_LOG.PLOGID
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    private String plogid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_SYS_LOG.ID
     *
     * @return the value of BC_SYS_LOG.ID
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_SYS_LOG.ID
     *
     * @param id the value for BC_SYS_LOG.ID
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_SYS_LOG.LOGOBJECT
     *
     * @return the value of BC_SYS_LOG.LOGOBJECT
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public String getLogobject() {
        return logobject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_SYS_LOG.LOGOBJECT
     *
     * @param logobject the value for BC_SYS_LOG.LOGOBJECT
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public void setLogobject(String logobject) {
        this.logobject = logobject == null ? null : logobject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_SYS_LOG.LOGTYPE
     *
     * @return the value of BC_SYS_LOG.LOGTYPE
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public BigDecimal getLogtype() {
        return logtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_SYS_LOG.LOGTYPE
     *
     * @param logtype the value for BC_SYS_LOG.LOGTYPE
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public void setLogtype(BigDecimal logtype) {
        this.logtype = logtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_SYS_LOG.LOGKIND
     *
     * @return the value of BC_SYS_LOG.LOGKIND
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public BigDecimal getLogkind() {
        return logkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_SYS_LOG.LOGKIND
     *
     * @param logkind the value for BC_SYS_LOG.LOGKIND
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public void setLogkind(BigDecimal logkind) {
        this.logkind = logkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_SYS_LOG.LOGDESC
     *
     * @return the value of BC_SYS_LOG.LOGDESC
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public String getLogdesc() {
        return logdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_SYS_LOG.LOGDESC
     *
     * @param logdesc the value for BC_SYS_LOG.LOGDESC
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public void setLogdesc(String logdesc) {
        this.logdesc = logdesc == null ? null : logdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_SYS_LOG.OPERTYPE
     *
     * @return the value of BC_SYS_LOG.OPERTYPE
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public String getOpertype() {
        return opertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_SYS_LOG.OPERTYPE
     *
     * @param opertype the value for BC_SYS_LOG.OPERTYPE
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public void setOpertype(String opertype) {
        this.opertype = opertype == null ? null : opertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_SYS_LOG.OPERUSER
     *
     * @return the value of BC_SYS_LOG.OPERUSER
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public String getOperuser() {
        return operuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_SYS_LOG.OPERUSER
     *
     * @param operuser the value for BC_SYS_LOG.OPERUSER
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public void setOperuser(String operuser) {
        this.operuser = operuser == null ? null : operuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_SYS_LOG.OPERIP
     *
     * @return the value of BC_SYS_LOG.OPERIP
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public String getOperip() {
        return operip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_SYS_LOG.OPERIP
     *
     * @param operip the value for BC_SYS_LOG.OPERIP
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public void setOperip(String operip) {
        this.operip = operip == null ? null : operip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_SYS_LOG.OPERDATE
     *
     * @return the value of BC_SYS_LOG.OPERDATE
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public String getOperdate() {
        return operdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_SYS_LOG.OPERDATE
     *
     * @param operdate the value for BC_SYS_LOG.OPERDATE
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public void setOperdate(String operdate) {
        this.operdate = operdate == null ? null : operdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_SYS_LOG.OPERRESULT
     *
     * @return the value of BC_SYS_LOG.OPERRESULT
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public String getOperresult() {
        return operresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_SYS_LOG.OPERRESULT
     *
     * @param operresult the value for BC_SYS_LOG.OPERRESULT
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public void setOperresult(String operresult) {
        this.operresult = operresult == null ? null : operresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_SYS_LOG.PLOGID
     *
     * @return the value of BC_SYS_LOG.PLOGID
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public String getPlogid() {
        return plogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_SYS_LOG.PLOGID
     *
     * @param plogid the value for BC_SYS_LOG.PLOGID
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public void setPlogid(String plogid) {
        this.plogid = plogid == null ? null : plogid.trim();
    }
}