package com.smartwasser.swrmq.model;

import java.math.BigDecimal;

public class BcSysResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_resource.ID
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_resource.PERMISSION
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_resource.NAME
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_resource.URL_VAL
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    private String urlVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_resource.FUNC_ID
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    private String funcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_resource.ICON
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_resource.SORT
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    private BigDecimal sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_resource.ID
     *
     * @return the value of bc_sys_resource.ID
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_resource.ID
     *
     * @param id the value for bc_sys_resource.ID
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_resource.PERMISSION
     *
     * @return the value of bc_sys_resource.PERMISSION
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_resource.PERMISSION
     *
     * @param permission the value for bc_sys_resource.PERMISSION
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_resource.NAME
     *
     * @return the value of bc_sys_resource.NAME
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_resource.NAME
     *
     * @param name the value for bc_sys_resource.NAME
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_resource.URL_VAL
     *
     * @return the value of bc_sys_resource.URL_VAL
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    public String getUrlVal() {
        return urlVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_resource.URL_VAL
     *
     * @param urlVal the value for bc_sys_resource.URL_VAL
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    public void setUrlVal(String urlVal) {
        this.urlVal = urlVal == null ? null : urlVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_resource.FUNC_ID
     *
     * @return the value of bc_sys_resource.FUNC_ID
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    public String getFuncId() {
        return funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_resource.FUNC_ID
     *
     * @param funcId the value for bc_sys_resource.FUNC_ID
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    public void setFuncId(String funcId) {
        this.funcId = funcId == null ? null : funcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_resource.ICON
     *
     * @return the value of bc_sys_resource.ICON
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_resource.ICON
     *
     * @param icon the value for bc_sys_resource.ICON
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_resource.SORT
     *
     * @return the value of bc_sys_resource.SORT
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    public BigDecimal getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_resource.SORT
     *
     * @param sort the value for bc_sys_resource.SORT
     *
     * @mbggenerated Wed Jul 20 19:16:45 CST 2016
     */
    public void setSort(BigDecimal sort) {
        this.sort = sort;
    }
}