package com.smartwasser.swrmq.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BcSysFuncExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bc_sys_func
     *
     * @mbggenerated Fri Jul 22 17:56:11 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bc_sys_func
     *
     * @mbggenerated Fri Jul 22 17:56:11 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bc_sys_func
     *
     * @mbggenerated Fri Jul 22 17:56:11 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_func
     *
     * @mbggenerated Fri Jul 22 17:56:11 CST 2016
     */
    public BcSysFuncExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_func
     *
     * @mbggenerated Fri Jul 22 17:56:11 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_func
     *
     * @mbggenerated Fri Jul 22 17:56:11 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_func
     *
     * @mbggenerated Fri Jul 22 17:56:11 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_func
     *
     * @mbggenerated Fri Jul 22 17:56:11 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_func
     *
     * @mbggenerated Fri Jul 22 17:56:11 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_func
     *
     * @mbggenerated Fri Jul 22 17:56:11 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_func
     *
     * @mbggenerated Fri Jul 22 17:56:11 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_func
     *
     * @mbggenerated Fri Jul 22 17:56:11 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_func
     *
     * @mbggenerated Fri Jul 22 17:56:11 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_sys_func
     *
     * @mbggenerated Fri Jul 22 17:56:11 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bc_sys_func
     *
     * @mbggenerated Fri Jul 22 17:56:11 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAppidIsNull() {
            addCriterion("APPID is null");
            return (Criteria) this;
        }

        public Criteria andAppidIsNotNull() {
            addCriterion("APPID is not null");
            return (Criteria) this;
        }

        public Criteria andAppidEqualTo(String value) {
            addCriterion("APPID =", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotEqualTo(String value) {
            addCriterion("APPID <>", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidGreaterThan(String value) {
            addCriterion("APPID >", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidGreaterThanOrEqualTo(String value) {
            addCriterion("APPID >=", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLessThan(String value) {
            addCriterion("APPID <", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLessThanOrEqualTo(String value) {
            addCriterion("APPID <=", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLike(String value) {
            addCriterion("APPID like", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotLike(String value) {
            addCriterion("APPID not like", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidIn(List<String> values) {
            addCriterion("APPID in", values, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotIn(List<String> values) {
            addCriterion("APPID not in", values, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidBetween(String value1, String value2) {
            addCriterion("APPID between", value1, value2, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotBetween(String value1, String value2) {
            addCriterion("APPID not between", value1, value2, "appid");
            return (Criteria) this;
        }

        public Criteria andParentidIsNull() {
            addCriterion("PARENTID is null");
            return (Criteria) this;
        }

        public Criteria andParentidIsNotNull() {
            addCriterion("PARENTID is not null");
            return (Criteria) this;
        }

        public Criteria andParentidEqualTo(String value) {
            addCriterion("PARENTID =", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotEqualTo(String value) {
            addCriterion("PARENTID <>", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThan(String value) {
            addCriterion("PARENTID >", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThanOrEqualTo(String value) {
            addCriterion("PARENTID >=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThan(String value) {
            addCriterion("PARENTID <", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThanOrEqualTo(String value) {
            addCriterion("PARENTID <=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLike(String value) {
            addCriterion("PARENTID like", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotLike(String value) {
            addCriterion("PARENTID not like", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidIn(List<String> values) {
            addCriterion("PARENTID in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotIn(List<String> values) {
            addCriterion("PARENTID not in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidBetween(String value1, String value2) {
            addCriterion("PARENTID between", value1, value2, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotBetween(String value1, String value2) {
            addCriterion("PARENTID not between", value1, value2, "parentid");
            return (Criteria) this;
        }

        public Criteria andFuncnamechIsNull() {
            addCriterion("FUNCNAMECH is null");
            return (Criteria) this;
        }

        public Criteria andFuncnamechIsNotNull() {
            addCriterion("FUNCNAMECH is not null");
            return (Criteria) this;
        }

        public Criteria andFuncnamechEqualTo(String value) {
            addCriterion("FUNCNAMECH =", value, "funcnamech");
            return (Criteria) this;
        }

        public Criteria andFuncnamechNotEqualTo(String value) {
            addCriterion("FUNCNAMECH <>", value, "funcnamech");
            return (Criteria) this;
        }

        public Criteria andFuncnamechGreaterThan(String value) {
            addCriterion("FUNCNAMECH >", value, "funcnamech");
            return (Criteria) this;
        }

        public Criteria andFuncnamechGreaterThanOrEqualTo(String value) {
            addCriterion("FUNCNAMECH >=", value, "funcnamech");
            return (Criteria) this;
        }

        public Criteria andFuncnamechLessThan(String value) {
            addCriterion("FUNCNAMECH <", value, "funcnamech");
            return (Criteria) this;
        }

        public Criteria andFuncnamechLessThanOrEqualTo(String value) {
            addCriterion("FUNCNAMECH <=", value, "funcnamech");
            return (Criteria) this;
        }

        public Criteria andFuncnamechLike(String value) {
            addCriterion("FUNCNAMECH like", value, "funcnamech");
            return (Criteria) this;
        }

        public Criteria andFuncnamechNotLike(String value) {
            addCriterion("FUNCNAMECH not like", value, "funcnamech");
            return (Criteria) this;
        }

        public Criteria andFuncnamechIn(List<String> values) {
            addCriterion("FUNCNAMECH in", values, "funcnamech");
            return (Criteria) this;
        }

        public Criteria andFuncnamechNotIn(List<String> values) {
            addCriterion("FUNCNAMECH not in", values, "funcnamech");
            return (Criteria) this;
        }

        public Criteria andFuncnamechBetween(String value1, String value2) {
            addCriterion("FUNCNAMECH between", value1, value2, "funcnamech");
            return (Criteria) this;
        }

        public Criteria andFuncnamechNotBetween(String value1, String value2) {
            addCriterion("FUNCNAMECH not between", value1, value2, "funcnamech");
            return (Criteria) this;
        }

        public Criteria andFuncnameenIsNull() {
            addCriterion("FUNCNAMEEN is null");
            return (Criteria) this;
        }

        public Criteria andFuncnameenIsNotNull() {
            addCriterion("FUNCNAMEEN is not null");
            return (Criteria) this;
        }

        public Criteria andFuncnameenEqualTo(String value) {
            addCriterion("FUNCNAMEEN =", value, "funcnameen");
            return (Criteria) this;
        }

        public Criteria andFuncnameenNotEqualTo(String value) {
            addCriterion("FUNCNAMEEN <>", value, "funcnameen");
            return (Criteria) this;
        }

        public Criteria andFuncnameenGreaterThan(String value) {
            addCriterion("FUNCNAMEEN >", value, "funcnameen");
            return (Criteria) this;
        }

        public Criteria andFuncnameenGreaterThanOrEqualTo(String value) {
            addCriterion("FUNCNAMEEN >=", value, "funcnameen");
            return (Criteria) this;
        }

        public Criteria andFuncnameenLessThan(String value) {
            addCriterion("FUNCNAMEEN <", value, "funcnameen");
            return (Criteria) this;
        }

        public Criteria andFuncnameenLessThanOrEqualTo(String value) {
            addCriterion("FUNCNAMEEN <=", value, "funcnameen");
            return (Criteria) this;
        }

        public Criteria andFuncnameenLike(String value) {
            addCriterion("FUNCNAMEEN like", value, "funcnameen");
            return (Criteria) this;
        }

        public Criteria andFuncnameenNotLike(String value) {
            addCriterion("FUNCNAMEEN not like", value, "funcnameen");
            return (Criteria) this;
        }

        public Criteria andFuncnameenIn(List<String> values) {
            addCriterion("FUNCNAMEEN in", values, "funcnameen");
            return (Criteria) this;
        }

        public Criteria andFuncnameenNotIn(List<String> values) {
            addCriterion("FUNCNAMEEN not in", values, "funcnameen");
            return (Criteria) this;
        }

        public Criteria andFuncnameenBetween(String value1, String value2) {
            addCriterion("FUNCNAMEEN between", value1, value2, "funcnameen");
            return (Criteria) this;
        }

        public Criteria andFuncnameenNotBetween(String value1, String value2) {
            addCriterion("FUNCNAMEEN not between", value1, value2, "funcnameen");
            return (Criteria) this;
        }

        public Criteria andFuncurlIsNull() {
            addCriterion("FUNCURL is null");
            return (Criteria) this;
        }

        public Criteria andFuncurlIsNotNull() {
            addCriterion("FUNCURL is not null");
            return (Criteria) this;
        }

        public Criteria andFuncurlEqualTo(String value) {
            addCriterion("FUNCURL =", value, "funcurl");
            return (Criteria) this;
        }

        public Criteria andFuncurlNotEqualTo(String value) {
            addCriterion("FUNCURL <>", value, "funcurl");
            return (Criteria) this;
        }

        public Criteria andFuncurlGreaterThan(String value) {
            addCriterion("FUNCURL >", value, "funcurl");
            return (Criteria) this;
        }

        public Criteria andFuncurlGreaterThanOrEqualTo(String value) {
            addCriterion("FUNCURL >=", value, "funcurl");
            return (Criteria) this;
        }

        public Criteria andFuncurlLessThan(String value) {
            addCriterion("FUNCURL <", value, "funcurl");
            return (Criteria) this;
        }

        public Criteria andFuncurlLessThanOrEqualTo(String value) {
            addCriterion("FUNCURL <=", value, "funcurl");
            return (Criteria) this;
        }

        public Criteria andFuncurlLike(String value) {
            addCriterion("FUNCURL like", value, "funcurl");
            return (Criteria) this;
        }

        public Criteria andFuncurlNotLike(String value) {
            addCriterion("FUNCURL not like", value, "funcurl");
            return (Criteria) this;
        }

        public Criteria andFuncurlIn(List<String> values) {
            addCriterion("FUNCURL in", values, "funcurl");
            return (Criteria) this;
        }

        public Criteria andFuncurlNotIn(List<String> values) {
            addCriterion("FUNCURL not in", values, "funcurl");
            return (Criteria) this;
        }

        public Criteria andFuncurlBetween(String value1, String value2) {
            addCriterion("FUNCURL between", value1, value2, "funcurl");
            return (Criteria) this;
        }

        public Criteria andFuncurlNotBetween(String value1, String value2) {
            addCriterion("FUNCURL not between", value1, value2, "funcurl");
            return (Criteria) this;
        }

        public Criteria andFuncdescIsNull() {
            addCriterion("FUNCDESC is null");
            return (Criteria) this;
        }

        public Criteria andFuncdescIsNotNull() {
            addCriterion("FUNCDESC is not null");
            return (Criteria) this;
        }

        public Criteria andFuncdescEqualTo(String value) {
            addCriterion("FUNCDESC =", value, "funcdesc");
            return (Criteria) this;
        }

        public Criteria andFuncdescNotEqualTo(String value) {
            addCriterion("FUNCDESC <>", value, "funcdesc");
            return (Criteria) this;
        }

        public Criteria andFuncdescGreaterThan(String value) {
            addCriterion("FUNCDESC >", value, "funcdesc");
            return (Criteria) this;
        }

        public Criteria andFuncdescGreaterThanOrEqualTo(String value) {
            addCriterion("FUNCDESC >=", value, "funcdesc");
            return (Criteria) this;
        }

        public Criteria andFuncdescLessThan(String value) {
            addCriterion("FUNCDESC <", value, "funcdesc");
            return (Criteria) this;
        }

        public Criteria andFuncdescLessThanOrEqualTo(String value) {
            addCriterion("FUNCDESC <=", value, "funcdesc");
            return (Criteria) this;
        }

        public Criteria andFuncdescLike(String value) {
            addCriterion("FUNCDESC like", value, "funcdesc");
            return (Criteria) this;
        }

        public Criteria andFuncdescNotLike(String value) {
            addCriterion("FUNCDESC not like", value, "funcdesc");
            return (Criteria) this;
        }

        public Criteria andFuncdescIn(List<String> values) {
            addCriterion("FUNCDESC in", values, "funcdesc");
            return (Criteria) this;
        }

        public Criteria andFuncdescNotIn(List<String> values) {
            addCriterion("FUNCDESC not in", values, "funcdesc");
            return (Criteria) this;
        }

        public Criteria andFuncdescBetween(String value1, String value2) {
            addCriterion("FUNCDESC between", value1, value2, "funcdesc");
            return (Criteria) this;
        }

        public Criteria andFuncdescNotBetween(String value1, String value2) {
            addCriterion("FUNCDESC not between", value1, value2, "funcdesc");
            return (Criteria) this;
        }

        public Criteria andFunccodeIsNull() {
            addCriterion("FUNCCODE is null");
            return (Criteria) this;
        }

        public Criteria andFunccodeIsNotNull() {
            addCriterion("FUNCCODE is not null");
            return (Criteria) this;
        }

        public Criteria andFunccodeEqualTo(String value) {
            addCriterion("FUNCCODE =", value, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeNotEqualTo(String value) {
            addCriterion("FUNCCODE <>", value, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeGreaterThan(String value) {
            addCriterion("FUNCCODE >", value, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeGreaterThanOrEqualTo(String value) {
            addCriterion("FUNCCODE >=", value, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeLessThan(String value) {
            addCriterion("FUNCCODE <", value, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeLessThanOrEqualTo(String value) {
            addCriterion("FUNCCODE <=", value, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeLike(String value) {
            addCriterion("FUNCCODE like", value, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeNotLike(String value) {
            addCriterion("FUNCCODE not like", value, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeIn(List<String> values) {
            addCriterion("FUNCCODE in", values, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeNotIn(List<String> values) {
            addCriterion("FUNCCODE not in", values, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeBetween(String value1, String value2) {
            addCriterion("FUNCCODE between", value1, value2, "funccode");
            return (Criteria) this;
        }

        public Criteria andFunccodeNotBetween(String value1, String value2) {
            addCriterion("FUNCCODE not between", value1, value2, "funccode");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNull() {
            addCriterion("PRIORITY is null");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNotNull() {
            addCriterion("PRIORITY is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityEqualTo(Long value) {
            addCriterion("PRIORITY =", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotEqualTo(Long value) {
            addCriterion("PRIORITY <>", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThan(Long value) {
            addCriterion("PRIORITY >", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThanOrEqualTo(Long value) {
            addCriterion("PRIORITY >=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThan(Long value) {
            addCriterion("PRIORITY <", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThanOrEqualTo(Long value) {
            addCriterion("PRIORITY <=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityIn(List<Long> values) {
            addCriterion("PRIORITY in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotIn(List<Long> values) {
            addCriterion("PRIORITY not in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityBetween(Long value1, Long value2) {
            addCriterion("PRIORITY between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotBetween(Long value1, Long value2) {
            addCriterion("PRIORITY not between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andIsmenuIsNull() {
            addCriterion("ISMENU is null");
            return (Criteria) this;
        }

        public Criteria andIsmenuIsNotNull() {
            addCriterion("ISMENU is not null");
            return (Criteria) this;
        }

        public Criteria andIsmenuEqualTo(Short value) {
            addCriterion("ISMENU =", value, "ismenu");
            return (Criteria) this;
        }

        public Criteria andIsmenuNotEqualTo(Short value) {
            addCriterion("ISMENU <>", value, "ismenu");
            return (Criteria) this;
        }

        public Criteria andIsmenuGreaterThan(Short value) {
            addCriterion("ISMENU >", value, "ismenu");
            return (Criteria) this;
        }

        public Criteria andIsmenuGreaterThanOrEqualTo(Short value) {
            addCriterion("ISMENU >=", value, "ismenu");
            return (Criteria) this;
        }

        public Criteria andIsmenuLessThan(Short value) {
            addCriterion("ISMENU <", value, "ismenu");
            return (Criteria) this;
        }

        public Criteria andIsmenuLessThanOrEqualTo(Short value) {
            addCriterion("ISMENU <=", value, "ismenu");
            return (Criteria) this;
        }

        public Criteria andIsmenuIn(List<Short> values) {
            addCriterion("ISMENU in", values, "ismenu");
            return (Criteria) this;
        }

        public Criteria andIsmenuNotIn(List<Short> values) {
            addCriterion("ISMENU not in", values, "ismenu");
            return (Criteria) this;
        }

        public Criteria andIsmenuBetween(Short value1, Short value2) {
            addCriterion("ISMENU between", value1, value2, "ismenu");
            return (Criteria) this;
        }

        public Criteria andIsmenuNotBetween(Short value1, Short value2) {
            addCriterion("ISMENU not between", value1, value2, "ismenu");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CREATETIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CREATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("CREATETIME =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("CREATETIME <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("CREATETIME >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATETIME >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("CREATETIME <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATETIME <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("CREATETIME in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("CREATETIME not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("CREATETIME between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATETIME not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andChfuncmidIsNull() {
            addCriterion("CHFUNCMID is null");
            return (Criteria) this;
        }

        public Criteria andChfuncmidIsNotNull() {
            addCriterion("CHFUNCMID is not null");
            return (Criteria) this;
        }

        public Criteria andChfuncmidEqualTo(Long value) {
            addCriterion("CHFUNCMID =", value, "chfuncmid");
            return (Criteria) this;
        }

        public Criteria andChfuncmidNotEqualTo(Long value) {
            addCriterion("CHFUNCMID <>", value, "chfuncmid");
            return (Criteria) this;
        }

        public Criteria andChfuncmidGreaterThan(Long value) {
            addCriterion("CHFUNCMID >", value, "chfuncmid");
            return (Criteria) this;
        }

        public Criteria andChfuncmidGreaterThanOrEqualTo(Long value) {
            addCriterion("CHFUNCMID >=", value, "chfuncmid");
            return (Criteria) this;
        }

        public Criteria andChfuncmidLessThan(Long value) {
            addCriterion("CHFUNCMID <", value, "chfuncmid");
            return (Criteria) this;
        }

        public Criteria andChfuncmidLessThanOrEqualTo(Long value) {
            addCriterion("CHFUNCMID <=", value, "chfuncmid");
            return (Criteria) this;
        }

        public Criteria andChfuncmidIn(List<Long> values) {
            addCriterion("CHFUNCMID in", values, "chfuncmid");
            return (Criteria) this;
        }

        public Criteria andChfuncmidNotIn(List<Long> values) {
            addCriterion("CHFUNCMID not in", values, "chfuncmid");
            return (Criteria) this;
        }

        public Criteria andChfuncmidBetween(Long value1, Long value2) {
            addCriterion("CHFUNCMID between", value1, value2, "chfuncmid");
            return (Criteria) this;
        }

        public Criteria andChfuncmidNotBetween(Long value1, Long value2) {
            addCriterion("CHFUNCMID not between", value1, value2, "chfuncmid");
            return (Criteria) this;
        }

        public Criteria andIsappIsNull() {
            addCriterion("isapp is null");
            return (Criteria) this;
        }

        public Criteria andIsappIsNotNull() {
            addCriterion("isapp is not null");
            return (Criteria) this;
        }

        public Criteria andIsappEqualTo(String value) {
            addCriterion("isapp =", value, "isapp");
            return (Criteria) this;
        }

        public Criteria andIsappNotEqualTo(String value) {
            addCriterion("isapp <>", value, "isapp");
            return (Criteria) this;
        }

        public Criteria andIsappGreaterThan(String value) {
            addCriterion("isapp >", value, "isapp");
            return (Criteria) this;
        }

        public Criteria andIsappGreaterThanOrEqualTo(String value) {
            addCriterion("isapp >=", value, "isapp");
            return (Criteria) this;
        }

        public Criteria andIsappLessThan(String value) {
            addCriterion("isapp <", value, "isapp");
            return (Criteria) this;
        }

        public Criteria andIsappLessThanOrEqualTo(String value) {
            addCriterion("isapp <=", value, "isapp");
            return (Criteria) this;
        }

        public Criteria andIsappLike(String value) {
            addCriterion("isapp like", value, "isapp");
            return (Criteria) this;
        }

        public Criteria andIsappNotLike(String value) {
            addCriterion("isapp not like", value, "isapp");
            return (Criteria) this;
        }

        public Criteria andIsappIn(List<String> values) {
            addCriterion("isapp in", values, "isapp");
            return (Criteria) this;
        }

        public Criteria andIsappNotIn(List<String> values) {
            addCriterion("isapp not in", values, "isapp");
            return (Criteria) this;
        }

        public Criteria andIsappBetween(String value1, String value2) {
            addCriterion("isapp between", value1, value2, "isapp");
            return (Criteria) this;
        }

        public Criteria andIsappNotBetween(String value1, String value2) {
            addCriterion("isapp not between", value1, value2, "isapp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bc_sys_func
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 22 17:56:11 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bc_sys_func
     *
     * @mbggenerated Fri Jul 22 17:56:11 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}