package com.smartwasser.swrmq.model;

public class BcSysResourceRight {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_resource_right.ID
     *
     * @mbggenerated Wed Jul 20 19:16:34 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_resource_right.ROLEID
     *
     * @mbggenerated Wed Jul 20 19:16:34 CST 2016
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_resource_right.RESOURCEID
     *
     * @mbggenerated Wed Jul 20 19:16:34 CST 2016
     */
    private String resourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_sys_resource_right.FUNCID
     *
     * @mbggenerated Wed Jul 20 19:16:34 CST 2016
     */
    private String funcid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_resource_right.ID
     *
     * @return the value of bc_sys_resource_right.ID
     *
     * @mbggenerated Wed Jul 20 19:16:34 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_resource_right.ID
     *
     * @param id the value for bc_sys_resource_right.ID
     *
     * @mbggenerated Wed Jul 20 19:16:34 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_resource_right.ROLEID
     *
     * @return the value of bc_sys_resource_right.ROLEID
     *
     * @mbggenerated Wed Jul 20 19:16:34 CST 2016
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_resource_right.ROLEID
     *
     * @param roleid the value for bc_sys_resource_right.ROLEID
     *
     * @mbggenerated Wed Jul 20 19:16:34 CST 2016
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_resource_right.RESOURCEID
     *
     * @return the value of bc_sys_resource_right.RESOURCEID
     *
     * @mbggenerated Wed Jul 20 19:16:34 CST 2016
     */
    public String getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_resource_right.RESOURCEID
     *
     * @param resourceid the value for bc_sys_resource_right.RESOURCEID
     *
     * @mbggenerated Wed Jul 20 19:16:34 CST 2016
     */
    public void setResourceid(String resourceid) {
        this.resourceid = resourceid == null ? null : resourceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_sys_resource_right.FUNCID
     *
     * @return the value of bc_sys_resource_right.FUNCID
     *
     * @mbggenerated Wed Jul 20 19:16:34 CST 2016
     */
    public String getFuncid() {
        return funcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_sys_resource_right.FUNCID
     *
     * @param funcid the value for bc_sys_resource_right.FUNCID
     *
     * @mbggenerated Wed Jul 20 19:16:34 CST 2016
     */
    public void setFuncid(String funcid) {
        this.funcid = funcid == null ? null : funcid.trim();
    }
}