package com.smartwasser.swrmq.model;

public class BcSysOrguser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_SYS_ORGUSER.DEPTID
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    private String deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_SYS_ORGUSER.USERID
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BC_SYS_ORGUSER.CURDEPT
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    private Long curdept;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_SYS_ORGUSER.DEPTID
     *
     * @return the value of BC_SYS_ORGUSER.DEPTID
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public String getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_SYS_ORGUSER.DEPTID
     *
     * @param deptid the value for BC_SYS_ORGUSER.DEPTID
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public void setDeptid(String deptid) {
        this.deptid = deptid == null ? null : deptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_SYS_ORGUSER.USERID
     *
     * @return the value of BC_SYS_ORGUSER.USERID
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_SYS_ORGUSER.USERID
     *
     * @param userid the value for BC_SYS_ORGUSER.USERID
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BC_SYS_ORGUSER.CURDEPT
     *
     * @return the value of BC_SYS_ORGUSER.CURDEPT
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public Long getCurdept() {
        return curdept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BC_SYS_ORGUSER.CURDEPT
     *
     * @param curdept the value for BC_SYS_ORGUSER.CURDEPT
     *
     * @mbggenerated Tue Jan 20 11:13:30 CST 2015
     */
    public void setCurdept(Long curdept) {
        this.curdept = curdept;
    }
}