package com.smartwasser.swrmq.model;

import java.io.Serializable;

public class ClientSysUserKey implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -6534866289540142972L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_sys_user.id
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_sys_user.username
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_sys_user.id
     *
     * @return the value of client_sys_user.id
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_sys_user.id
     *
     * @param id the value for client_sys_user.id
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_sys_user.username
     *
     * @return the value of client_sys_user.username
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_sys_user.username
     *
     * @param username the value for client_sys_user.username
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }
}