package com.smartwasser.swrmq.model;

import java.util.Date;

public class ClientUnitInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_unit_info.id
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_unit_info.client_unit_name_ch
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    private String clientUnitNameCh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_unit_info.client_unit_name_en
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    private String clientUnitNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_unit_info.address
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_unit_info.second_level_domain
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    private String secondLevelDomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_unit_info.state
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_unit_info.create_time
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_unit_info.creator
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_unit_info.update_time
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_unit_info.remark
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_unit_info.del_flag
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_unit_info.unitcode
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    private String unitcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_unit_info.id
     *
     * @return the value of client_unit_info.id
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_unit_info.id
     *
     * @param id the value for client_unit_info.id
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_unit_info.client_unit_name_ch
     *
     * @return the value of client_unit_info.client_unit_name_ch
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public String getClientUnitNameCh() {
        return clientUnitNameCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_unit_info.client_unit_name_ch
     *
     * @param clientUnitNameCh the value for client_unit_info.client_unit_name_ch
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public void setClientUnitNameCh(String clientUnitNameCh) {
        this.clientUnitNameCh = clientUnitNameCh == null ? null : clientUnitNameCh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_unit_info.client_unit_name_en
     *
     * @return the value of client_unit_info.client_unit_name_en
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public String getClientUnitNameEn() {
        return clientUnitNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_unit_info.client_unit_name_en
     *
     * @param clientUnitNameEn the value for client_unit_info.client_unit_name_en
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public void setClientUnitNameEn(String clientUnitNameEn) {
        this.clientUnitNameEn = clientUnitNameEn == null ? null : clientUnitNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_unit_info.address
     *
     * @return the value of client_unit_info.address
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_unit_info.address
     *
     * @param address the value for client_unit_info.address
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_unit_info.second_level_domain
     *
     * @return the value of client_unit_info.second_level_domain
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public String getSecondLevelDomain() {
        return secondLevelDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_unit_info.second_level_domain
     *
     * @param secondLevelDomain the value for client_unit_info.second_level_domain
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public void setSecondLevelDomain(String secondLevelDomain) {
        this.secondLevelDomain = secondLevelDomain == null ? null : secondLevelDomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_unit_info.state
     *
     * @return the value of client_unit_info.state
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_unit_info.state
     *
     * @param state the value for client_unit_info.state
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_unit_info.create_time
     *
     * @return the value of client_unit_info.create_time
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_unit_info.create_time
     *
     * @param createTime the value for client_unit_info.create_time
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_unit_info.creator
     *
     * @return the value of client_unit_info.creator
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_unit_info.creator
     *
     * @param creator the value for client_unit_info.creator
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_unit_info.update_time
     *
     * @return the value of client_unit_info.update_time
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_unit_info.update_time
     *
     * @param updateTime the value for client_unit_info.update_time
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_unit_info.remark
     *
     * @return the value of client_unit_info.remark
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_unit_info.remark
     *
     * @param remark the value for client_unit_info.remark
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_unit_info.del_flag
     *
     * @return the value of client_unit_info.del_flag
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_unit_info.del_flag
     *
     * @param delFlag the value for client_unit_info.del_flag
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_unit_info.unitcode
     *
     * @return the value of client_unit_info.unitcode
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public String getUnitcode() {
        return unitcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_unit_info.unitcode
     *
     * @param unitcode the value for client_unit_info.unitcode
     *
     * @mbggenerated Wed Jul 20 10:25:23 CST 2016
     */
    public void setUnitcode(String unitcode) {
        this.unitcode = unitcode == null ? null : unitcode.trim();
    }
}