package com.smartwasser.swrmq.model;

import java.io.Serializable;
import java.util.Date;

public class ClientSysUser extends ClientSysUserKey implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -1423909672877401163L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_sys_user.password
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_sys_user.usernamecn
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    private String usernamecn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_sys_user.email
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_sys_user.fk_client_unti_id
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    private String fkClientUntiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_sys_user.state
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_sys_user.create_time
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_sys_user.creator
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_sys_user.update_time
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_sys_user.remark
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_sys_user.del_flag
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_sys_user.super_admin_flag
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    private String superAdminFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_sys_user.password
     *
     * @return the value of client_sys_user.password
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_sys_user.password
     *
     * @param password the value for client_sys_user.password
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_sys_user.usernamecn
     *
     * @return the value of client_sys_user.usernamecn
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public String getUsernamecn() {
        return usernamecn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_sys_user.usernamecn
     *
     * @param usernamecn the value for client_sys_user.usernamecn
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public void setUsernamecn(String usernamecn) {
        this.usernamecn = usernamecn == null ? null : usernamecn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_sys_user.email
     *
     * @return the value of client_sys_user.email
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_sys_user.email
     *
     * @param email the value for client_sys_user.email
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_sys_user.fk_client_unti_id
     *
     * @return the value of client_sys_user.fk_client_unti_id
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public String getFkClientUntiId() {
        return fkClientUntiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_sys_user.fk_client_unti_id
     *
     * @param fkClientUntiId the value for client_sys_user.fk_client_unti_id
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public void setFkClientUntiId(String fkClientUntiId) {
        this.fkClientUntiId = fkClientUntiId == null ? null : fkClientUntiId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_sys_user.state
     *
     * @return the value of client_sys_user.state
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_sys_user.state
     *
     * @param state the value for client_sys_user.state
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_sys_user.create_time
     *
     * @return the value of client_sys_user.create_time
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_sys_user.create_time
     *
     * @param createTime the value for client_sys_user.create_time
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_sys_user.creator
     *
     * @return the value of client_sys_user.creator
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_sys_user.creator
     *
     * @param creator the value for client_sys_user.creator
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_sys_user.update_time
     *
     * @return the value of client_sys_user.update_time
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_sys_user.update_time
     *
     * @param updateTime the value for client_sys_user.update_time
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_sys_user.remark
     *
     * @return the value of client_sys_user.remark
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_sys_user.remark
     *
     * @param remark the value for client_sys_user.remark
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_sys_user.del_flag
     *
     * @return the value of client_sys_user.del_flag
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_sys_user.del_flag
     *
     * @param delFlag the value for client_sys_user.del_flag
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_sys_user.super_admin_flag
     *
     * @return the value of client_sys_user.super_admin_flag
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public String getSuperAdminFlag() {
        return superAdminFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_sys_user.super_admin_flag
     *
     * @param superAdminFlag the value for client_sys_user.super_admin_flag
     *
     * @mbggenerated Wed Jul 20 10:25:37 CST 2016
     */
    public void setSuperAdminFlag(String superAdminFlag) {
        this.superAdminFlag = superAdminFlag == null ? null : superAdminFlag.trim();
    }
}