package com.smartwasser.swrmq.model;

import java.util.Date;

public class DataSource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.id
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.schema_name
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    private String schemaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.fk_system_id
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    private String fkSystemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.run_state
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    private String runState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.last_run_time
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    private Date lastRunTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.use_state
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    private String useState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.create_time
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.creator
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.update_time
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.remark
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.del_flag
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.id
     *
     * @return the value of data_source.id
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.id
     *
     * @param id the value for data_source.id
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.schema_name
     *
     * @return the value of data_source.schema_name
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public String getSchemaName() {
        return schemaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.schema_name
     *
     * @param schemaName the value for data_source.schema_name
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public void setSchemaName(String schemaName) {
        this.schemaName = schemaName == null ? null : schemaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.fk_system_id
     *
     * @return the value of data_source.fk_system_id
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public String getFkSystemId() {
        return fkSystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.fk_system_id
     *
     * @param fkSystemId the value for data_source.fk_system_id
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public void setFkSystemId(String fkSystemId) {
        this.fkSystemId = fkSystemId == null ? null : fkSystemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.run_state
     *
     * @return the value of data_source.run_state
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public String getRunState() {
        return runState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.run_state
     *
     * @param runState the value for data_source.run_state
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public void setRunState(String runState) {
        this.runState = runState == null ? null : runState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.last_run_time
     *
     * @return the value of data_source.last_run_time
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public Date getLastRunTime() {
        return lastRunTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.last_run_time
     *
     * @param lastRunTime the value for data_source.last_run_time
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public void setLastRunTime(Date lastRunTime) {
        this.lastRunTime = lastRunTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.use_state
     *
     * @return the value of data_source.use_state
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public String getUseState() {
        return useState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.use_state
     *
     * @param useState the value for data_source.use_state
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public void setUseState(String useState) {
        this.useState = useState == null ? null : useState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.create_time
     *
     * @return the value of data_source.create_time
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.create_time
     *
     * @param createTime the value for data_source.create_time
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.creator
     *
     * @return the value of data_source.creator
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.creator
     *
     * @param creator the value for data_source.creator
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.update_time
     *
     * @return the value of data_source.update_time
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.update_time
     *
     * @param updateTime the value for data_source.update_time
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.remark
     *
     * @return the value of data_source.remark
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.remark
     *
     * @param remark the value for data_source.remark
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.del_flag
     *
     * @return the value of data_source.del_flag
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.del_flag
     *
     * @param delFlag the value for data_source.del_flag
     *
     * @mbggenerated Wed Jul 20 10:24:01 CST 2016
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
}