package com.smartwasser.swrmq.model;

import java.util.Date;

public class ModelAccredit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_accredit.id
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_accredit.fk_appid
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    private String fkAppid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_accredit.fk_sys_auth_id
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    private String fkSysAuthId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_accredit.state
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_accredit.create_time
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_accredit.creator
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_accredit.update_time
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_accredit.remark
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_accredit.delflag
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    private String delflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_accredit.id
     *
     * @return the value of model_accredit.id
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_accredit.id
     *
     * @param id the value for model_accredit.id
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_accredit.fk_appid
     *
     * @return the value of model_accredit.fk_appid
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    public String getFkAppid() {
        return fkAppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_accredit.fk_appid
     *
     * @param fkAppid the value for model_accredit.fk_appid
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    public void setFkAppid(String fkAppid) {
        this.fkAppid = fkAppid == null ? null : fkAppid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_accredit.fk_sys_auth_id
     *
     * @return the value of model_accredit.fk_sys_auth_id
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    public String getFkSysAuthId() {
        return fkSysAuthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_accredit.fk_sys_auth_id
     *
     * @param fkSysAuthId the value for model_accredit.fk_sys_auth_id
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    public void setFkSysAuthId(String fkSysAuthId) {
        this.fkSysAuthId = fkSysAuthId == null ? null : fkSysAuthId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_accredit.state
     *
     * @return the value of model_accredit.state
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_accredit.state
     *
     * @param state the value for model_accredit.state
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_accredit.create_time
     *
     * @return the value of model_accredit.create_time
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_accredit.create_time
     *
     * @param createTime the value for model_accredit.create_time
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_accredit.creator
     *
     * @return the value of model_accredit.creator
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_accredit.creator
     *
     * @param creator the value for model_accredit.creator
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_accredit.update_time
     *
     * @return the value of model_accredit.update_time
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_accredit.update_time
     *
     * @param updateTime the value for model_accredit.update_time
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_accredit.remark
     *
     * @return the value of model_accredit.remark
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_accredit.remark
     *
     * @param remark the value for model_accredit.remark
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_accredit.delflag
     *
     * @return the value of model_accredit.delflag
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    public String getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_accredit.delflag
     *
     * @param delflag the value for model_accredit.delflag
     *
     * @mbggenerated Wed Jul 20 10:23:52 CST 2016
     */
    public void setDelflag(String delflag) {
        this.delflag = delflag == null ? null : delflag.trim();
    }
}