package com.smartwasser.swrmq.model;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;

public class SubSysFunc implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -3673525922376590833L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_sys_func.id
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_sys_func.appid
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_sys_func.parentid
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_sys_func.funcnamech
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    private String funcnamech;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_sys_func.funcnameen
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    private String funcnameen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_sys_func.funcurl
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    private String funcurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_sys_func.funcdesc
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    private String funcdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_sys_func.funccode
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    private String funccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_sys_func.priority
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    private Long priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_sys_func.ismenu
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    private Short ismenu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_sys_func.chfuncmid
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    private Long chfuncmid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_sys_func.isapp
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    private String isapp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_sys_func.fk_system_id
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    private String fkSystemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_sys_func.createtime
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_sys_func.creator
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_sys_func.del_flag
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_sys_func.updatetime
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_sys_func.icon
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    private byte[] icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_sys_func.id
     *
     * @return the value of sub_sys_func.id
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_sys_func.id
     *
     * @param id the value for sub_sys_func.id
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_sys_func.appid
     *
     * @return the value of sub_sys_func.appid
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_sys_func.appid
     *
     * @param appid the value for sub_sys_func.appid
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_sys_func.parentid
     *
     * @return the value of sub_sys_func.parentid
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_sys_func.parentid
     *
     * @param parentid the value for sub_sys_func.parentid
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_sys_func.funcnamech
     *
     * @return the value of sub_sys_func.funcnamech
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public String getFuncnamech() {
        return funcnamech;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_sys_func.funcnamech
     *
     * @param funcnamech the value for sub_sys_func.funcnamech
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public void setFuncnamech(String funcnamech) {
        this.funcnamech = funcnamech == null ? null : funcnamech.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_sys_func.funcnameen
     *
     * @return the value of sub_sys_func.funcnameen
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public String getFuncnameen() {
        return funcnameen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_sys_func.funcnameen
     *
     * @param funcnameen the value for sub_sys_func.funcnameen
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public void setFuncnameen(String funcnameen) {
        this.funcnameen = funcnameen == null ? null : funcnameen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_sys_func.funcurl
     *
     * @return the value of sub_sys_func.funcurl
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public String getFuncurl() {
        return funcurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_sys_func.funcurl
     *
     * @param funcurl the value for sub_sys_func.funcurl
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public void setFuncurl(String funcurl) {
        this.funcurl = funcurl == null ? null : funcurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_sys_func.funcdesc
     *
     * @return the value of sub_sys_func.funcdesc
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public String getFuncdesc() {
        return funcdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_sys_func.funcdesc
     *
     * @param funcdesc the value for sub_sys_func.funcdesc
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public void setFuncdesc(String funcdesc) {
        this.funcdesc = funcdesc == null ? null : funcdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_sys_func.funccode
     *
     * @return the value of sub_sys_func.funccode
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public String getFunccode() {
        return funccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_sys_func.funccode
     *
     * @param funccode the value for sub_sys_func.funccode
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public void setFunccode(String funccode) {
        this.funccode = funccode == null ? null : funccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_sys_func.priority
     *
     * @return the value of sub_sys_func.priority
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public Long getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_sys_func.priority
     *
     * @param priority the value for sub_sys_func.priority
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public void setPriority(Long priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_sys_func.ismenu
     *
     * @return the value of sub_sys_func.ismenu
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public Short getIsmenu() {
        return ismenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_sys_func.ismenu
     *
     * @param ismenu the value for sub_sys_func.ismenu
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public void setIsmenu(Short ismenu) {
        this.ismenu = ismenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_sys_func.chfuncmid
     *
     * @return the value of sub_sys_func.chfuncmid
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public Long getChfuncmid() {
        return chfuncmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_sys_func.chfuncmid
     *
     * @param chfuncmid the value for sub_sys_func.chfuncmid
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public void setChfuncmid(Long chfuncmid) {
        this.chfuncmid = chfuncmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_sys_func.isapp
     *
     * @return the value of sub_sys_func.isapp
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public String getIsapp() {
        return isapp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_sys_func.isapp
     *
     * @param isapp the value for sub_sys_func.isapp
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public void setIsapp(String isapp) {
        this.isapp = isapp == null ? null : isapp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_sys_func.fk_system_id
     *
     * @return the value of sub_sys_func.fk_system_id
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public String getFkSystemId() {
        return fkSystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_sys_func.fk_system_id
     *
     * @param fkSystemId the value for sub_sys_func.fk_system_id
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public void setFkSystemId(String fkSystemId) {
        this.fkSystemId = fkSystemId == null ? null : fkSystemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_sys_func.createtime
     *
     * @return the value of sub_sys_func.createtime
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_sys_func.createtime
     *
     * @param createtime the value for sub_sys_func.createtime
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_sys_func.creator
     *
     * @return the value of sub_sys_func.creator
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_sys_func.creator
     *
     * @param creator the value for sub_sys_func.creator
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_sys_func.del_flag
     *
     * @return the value of sub_sys_func.del_flag
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_sys_func.del_flag
     *
     * @param delFlag the value for sub_sys_func.del_flag
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_sys_func.updatetime
     *
     * @return the value of sub_sys_func.updatetime
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_sys_func.updatetime
     *
     * @param updatetime the value for sub_sys_func.updatetime
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_sys_func.icon
     *
     * @return the value of sub_sys_func.icon
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public byte[] getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_sys_func.icon
     *
     * @param icon the value for sub_sys_func.icon
     *
     * @mbggenerated Fri Jul 22 18:04:39 CST 2016
     */
    public void setIcon(byte[] icon) {
        this.icon = icon;
    }
    
    public Map<String,String> schema;

	public Map<String, String> getSchema() {
		return schema;
	}

	public void setSchema(Map<String, String> schema) {
		this.schema = schema;
	}
}