package com.smartwasser.swrmq.model;

public class SubSysInfoWithBLOBs extends SubSysInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_sys_info.icon_normal
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    private byte[] iconNormal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_sys_info.icon_click
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    private byte[] iconClick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_sys_info.icon_disable
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    private byte[] iconDisable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_sys_info.icon_normal
     *
     * @return the value of sub_sys_info.icon_normal
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    public byte[] getIconNormal() {
        return iconNormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_sys_info.icon_normal
     *
     * @param iconNormal the value for sub_sys_info.icon_normal
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    public void setIconNormal(byte[] iconNormal) {
        this.iconNormal = iconNormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_sys_info.icon_click
     *
     * @return the value of sub_sys_info.icon_click
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    public byte[] getIconClick() {
        return iconClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_sys_info.icon_click
     *
     * @param iconClick the value for sub_sys_info.icon_click
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    public void setIconClick(byte[] iconClick) {
        this.iconClick = iconClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_sys_info.icon_disable
     *
     * @return the value of sub_sys_info.icon_disable
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    public byte[] getIconDisable() {
        return iconDisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_sys_info.icon_disable
     *
     * @param iconDisable the value for sub_sys_info.icon_disable
     *
     * @mbggenerated Wed Jul 20 10:23:24 CST 2016
     */
    public void setIconDisable(byte[] iconDisable) {
        this.iconDisable = iconDisable;
    }
}