package com.smartwasser.swrmq.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SystemAccreditExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public SystemAccreditExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFkBusinessUnitCodeIsNull() {
            addCriterion("fk_business_unit_code is null");
            return (Criteria) this;
        }

        public Criteria andFkBusinessUnitCodeIsNotNull() {
            addCriterion("fk_business_unit_code is not null");
            return (Criteria) this;
        }

        public Criteria andFkBusinessUnitCodeEqualTo(String value) {
            addCriterion("fk_business_unit_code =", value, "fkBusinessUnitCode");
            return (Criteria) this;
        }

        public Criteria andFkBusinessUnitCodeNotEqualTo(String value) {
            addCriterion("fk_business_unit_code <>", value, "fkBusinessUnitCode");
            return (Criteria) this;
        }

        public Criteria andFkBusinessUnitCodeGreaterThan(String value) {
            addCriterion("fk_business_unit_code >", value, "fkBusinessUnitCode");
            return (Criteria) this;
        }

        public Criteria andFkBusinessUnitCodeGreaterThanOrEqualTo(String value) {
            addCriterion("fk_business_unit_code >=", value, "fkBusinessUnitCode");
            return (Criteria) this;
        }

        public Criteria andFkBusinessUnitCodeLessThan(String value) {
            addCriterion("fk_business_unit_code <", value, "fkBusinessUnitCode");
            return (Criteria) this;
        }

        public Criteria andFkBusinessUnitCodeLessThanOrEqualTo(String value) {
            addCriterion("fk_business_unit_code <=", value, "fkBusinessUnitCode");
            return (Criteria) this;
        }

        public Criteria andFkBusinessUnitCodeLike(String value) {
            addCriterion("fk_business_unit_code like", value, "fkBusinessUnitCode");
            return (Criteria) this;
        }

        public Criteria andFkBusinessUnitCodeNotLike(String value) {
            addCriterion("fk_business_unit_code not like", value, "fkBusinessUnitCode");
            return (Criteria) this;
        }

        public Criteria andFkBusinessUnitCodeIn(List<String> values) {
            addCriterion("fk_business_unit_code in", values, "fkBusinessUnitCode");
            return (Criteria) this;
        }

        public Criteria andFkBusinessUnitCodeNotIn(List<String> values) {
            addCriterion("fk_business_unit_code not in", values, "fkBusinessUnitCode");
            return (Criteria) this;
        }

        public Criteria andFkBusinessUnitCodeBetween(String value1, String value2) {
            addCriterion("fk_business_unit_code between", value1, value2, "fkBusinessUnitCode");
            return (Criteria) this;
        }

        public Criteria andFkBusinessUnitCodeNotBetween(String value1, String value2) {
            addCriterion("fk_business_unit_code not between", value1, value2, "fkBusinessUnitCode");
            return (Criteria) this;
        }

        public Criteria andFkSystemIdIsNull() {
            addCriterion("fk_system_id is null");
            return (Criteria) this;
        }

        public Criteria andFkSystemIdIsNotNull() {
            addCriterion("fk_system_id is not null");
            return (Criteria) this;
        }

        public Criteria andFkSystemIdEqualTo(String value) {
            addCriterion("fk_system_id =", value, "fkSystemId");
            return (Criteria) this;
        }

        public Criteria andFkSystemIdNotEqualTo(String value) {
            addCriterion("fk_system_id <>", value, "fkSystemId");
            return (Criteria) this;
        }

        public Criteria andFkSystemIdGreaterThan(String value) {
            addCriterion("fk_system_id >", value, "fkSystemId");
            return (Criteria) this;
        }

        public Criteria andFkSystemIdGreaterThanOrEqualTo(String value) {
            addCriterion("fk_system_id >=", value, "fkSystemId");
            return (Criteria) this;
        }

        public Criteria andFkSystemIdLessThan(String value) {
            addCriterion("fk_system_id <", value, "fkSystemId");
            return (Criteria) this;
        }

        public Criteria andFkSystemIdLessThanOrEqualTo(String value) {
            addCriterion("fk_system_id <=", value, "fkSystemId");
            return (Criteria) this;
        }

        public Criteria andFkSystemIdLike(String value) {
            addCriterion("fk_system_id like", value, "fkSystemId");
            return (Criteria) this;
        }

        public Criteria andFkSystemIdNotLike(String value) {
            addCriterion("fk_system_id not like", value, "fkSystemId");
            return (Criteria) this;
        }

        public Criteria andFkSystemIdIn(List<String> values) {
            addCriterion("fk_system_id in", values, "fkSystemId");
            return (Criteria) this;
        }

        public Criteria andFkSystemIdNotIn(List<String> values) {
            addCriterion("fk_system_id not in", values, "fkSystemId");
            return (Criteria) this;
        }

        public Criteria andFkSystemIdBetween(String value1, String value2) {
            addCriterion("fk_system_id between", value1, value2, "fkSystemId");
            return (Criteria) this;
        }

        public Criteria andFkSystemIdNotBetween(String value1, String value2) {
            addCriterion("fk_system_id not between", value1, value2, "fkSystemId");
            return (Criteria) this;
        }

        public Criteria andFkSchemaIdIsNull() {
            addCriterion("fk_schema_id is null");
            return (Criteria) this;
        }

        public Criteria andFkSchemaIdIsNotNull() {
            addCriterion("fk_schema_id is not null");
            return (Criteria) this;
        }

        public Criteria andFkSchemaIdEqualTo(String value) {
            addCriterion("fk_schema_id =", value, "fkSchemaId");
            return (Criteria) this;
        }

        public Criteria andFkSchemaIdNotEqualTo(String value) {
            addCriterion("fk_schema_id <>", value, "fkSchemaId");
            return (Criteria) this;
        }

        public Criteria andFkSchemaIdGreaterThan(String value) {
            addCriterion("fk_schema_id >", value, "fkSchemaId");
            return (Criteria) this;
        }

        public Criteria andFkSchemaIdGreaterThanOrEqualTo(String value) {
            addCriterion("fk_schema_id >=", value, "fkSchemaId");
            return (Criteria) this;
        }

        public Criteria andFkSchemaIdLessThan(String value) {
            addCriterion("fk_schema_id <", value, "fkSchemaId");
            return (Criteria) this;
        }

        public Criteria andFkSchemaIdLessThanOrEqualTo(String value) {
            addCriterion("fk_schema_id <=", value, "fkSchemaId");
            return (Criteria) this;
        }

        public Criteria andFkSchemaIdLike(String value) {
            addCriterion("fk_schema_id like", value, "fkSchemaId");
            return (Criteria) this;
        }

        public Criteria andFkSchemaIdNotLike(String value) {
            addCriterion("fk_schema_id not like", value, "fkSchemaId");
            return (Criteria) this;
        }

        public Criteria andFkSchemaIdIn(List<String> values) {
            addCriterion("fk_schema_id in", values, "fkSchemaId");
            return (Criteria) this;
        }

        public Criteria andFkSchemaIdNotIn(List<String> values) {
            addCriterion("fk_schema_id not in", values, "fkSchemaId");
            return (Criteria) this;
        }

        public Criteria andFkSchemaIdBetween(String value1, String value2) {
            addCriterion("fk_schema_id between", value1, value2, "fkSchemaId");
            return (Criteria) this;
        }

        public Criteria andFkSchemaIdNotBetween(String value1, String value2) {
            addCriterion("fk_schema_id not between", value1, value2, "fkSchemaId");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(String value) {
            addCriterion("del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(String value) {
            addCriterion("del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(String value) {
            addCriterion("del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(String value) {
            addCriterion("del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(String value) {
            addCriterion("del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(String value) {
            addCriterion("del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLike(String value) {
            addCriterion("del_flag like", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotLike(String value) {
            addCriterion("del_flag not like", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<String> values) {
            addCriterion("del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<String> values) {
            addCriterion("del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(String value1, String value2) {
            addCriterion("del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(String value1, String value2) {
            addCriterion("del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_accredit
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 20 10:23:13 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_accredit
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}