package com.smartwasser.swrmq.model;

import java.util.Date;

public class SystemAccredit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_accredit.id
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_accredit.fk_business_unit_code
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    private String fkBusinessUnitCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_accredit.fk_system_id
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    private String fkSystemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_accredit.fk_schema_id
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    private String fkSchemaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_accredit.state
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_accredit.create_time
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_accredit.creator
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_accredit.update_time
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_accredit.remark
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_accredit.del_flag
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_accredit.id
     *
     * @return the value of system_accredit.id
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_accredit.id
     *
     * @param id the value for system_accredit.id
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_accredit.fk_business_unit_code
     *
     * @return the value of system_accredit.fk_business_unit_code
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public String getFkBusinessUnitCode() {
        return fkBusinessUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_accredit.fk_business_unit_code
     *
     * @param fkBusinessUnitCode the value for system_accredit.fk_business_unit_code
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public void setFkBusinessUnitCode(String fkBusinessUnitCode) {
        this.fkBusinessUnitCode = fkBusinessUnitCode == null ? null : fkBusinessUnitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_accredit.fk_system_id
     *
     * @return the value of system_accredit.fk_system_id
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public String getFkSystemId() {
        return fkSystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_accredit.fk_system_id
     *
     * @param fkSystemId the value for system_accredit.fk_system_id
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public void setFkSystemId(String fkSystemId) {
        this.fkSystemId = fkSystemId == null ? null : fkSystemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_accredit.fk_schema_id
     *
     * @return the value of system_accredit.fk_schema_id
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public String getFkSchemaId() {
        return fkSchemaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_accredit.fk_schema_id
     *
     * @param fkSchemaId the value for system_accredit.fk_schema_id
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public void setFkSchemaId(String fkSchemaId) {
        this.fkSchemaId = fkSchemaId == null ? null : fkSchemaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_accredit.state
     *
     * @return the value of system_accredit.state
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_accredit.state
     *
     * @param state the value for system_accredit.state
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_accredit.create_time
     *
     * @return the value of system_accredit.create_time
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_accredit.create_time
     *
     * @param createTime the value for system_accredit.create_time
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_accredit.creator
     *
     * @return the value of system_accredit.creator
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_accredit.creator
     *
     * @param creator the value for system_accredit.creator
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_accredit.update_time
     *
     * @return the value of system_accredit.update_time
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_accredit.update_time
     *
     * @param updateTime the value for system_accredit.update_time
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_accredit.remark
     *
     * @return the value of system_accredit.remark
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_accredit.remark
     *
     * @param remark the value for system_accredit.remark
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_accredit.del_flag
     *
     * @return the value of system_accredit.del_flag
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_accredit.del_flag
     *
     * @param delFlag the value for system_accredit.del_flag
     *
     * @mbggenerated Wed Jul 20 10:23:13 CST 2016
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
}