package com.smartwasser.swrmq.model;

import java.util.Date;

public class SystemAllocation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_allocation.fk_system_id
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    private String fkSystemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_allocation.user_id
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_allocation.allocation_person
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    private String allocationPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_allocation.create_time
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_allocation.fk_business_unit_code
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    private String fkBusinessUnitCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_allocation.fk_system_id
     *
     * @return the value of system_allocation.fk_system_id
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    public String getFkSystemId() {
        return fkSystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_allocation.fk_system_id
     *
     * @param fkSystemId the value for system_allocation.fk_system_id
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    public void setFkSystemId(String fkSystemId) {
        this.fkSystemId = fkSystemId == null ? null : fkSystemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_allocation.user_id
     *
     * @return the value of system_allocation.user_id
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_allocation.user_id
     *
     * @param userId the value for system_allocation.user_id
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_allocation.allocation_person
     *
     * @return the value of system_allocation.allocation_person
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    public String getAllocationPerson() {
        return allocationPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_allocation.allocation_person
     *
     * @param allocationPerson the value for system_allocation.allocation_person
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    public void setAllocationPerson(String allocationPerson) {
        this.allocationPerson = allocationPerson == null ? null : allocationPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_allocation.create_time
     *
     * @return the value of system_allocation.create_time
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_allocation.create_time
     *
     * @param createTime the value for system_allocation.create_time
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_allocation.fk_business_unit_code
     *
     * @return the value of system_allocation.fk_business_unit_code
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    public String getFkBusinessUnitCode() {
        return fkBusinessUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_allocation.fk_business_unit_code
     *
     * @param fkBusinessUnitCode the value for system_allocation.fk_business_unit_code
     *
     * @mbggenerated Wed Jul 20 10:22:59 CST 2016
     */
    public void setFkBusinessUnitCode(String fkBusinessUnitCode) {
        this.fkBusinessUnitCode = fkBusinessUnitCode == null ? null : fkBusinessUnitCode.trim();
    }
}